Scripting of Aluve App
benedictnkosi/aluve_property_management_tests pull request #8
Opened 2022-08-10 13:37 UTC by MlulekiN

2022-08-10 13:41 UTC, benedictnkosi requested changes

2022-08-10 13:41 UTC, benedictnkosi commented on src/test/java/stepDefinition/BookNowTopMenuSteps.java
> +public class BookNowTopMenuSteps {
have one file for menu steps

2022-08-10 13:41 UTC, benedictnkosi commented on src/test/java/stepDefinition/BookNowTopMenuSteps.java
> +    @Then("User validates content form is displayed")
what is content form?

2022-08-10 13:41 UTC, benedictnkosi commented on src/test/java/stepDefinition/BookNowTopMenuSteps.java
> +    @Then("User validates content form is displayed")
Do you meaning the booking form?

2022-08-10 13:41 UTC, benedictnkosi commented on src/test/java/stepDefinition/BookNowTopMenuSteps.java
> +        WebElement bookNowContentPage = driver.findElement(BookNowPage.contentForm);
what is bookNowContentPage

2022-08-12 12:48 UTC, MlulekiN commented on src/test/java/stepDefinition/BookNowTopMenuSteps.java
> +    @Then("User validates content form is displayed")
Done

2022-08-12 13:00 UTC, MlulekiN commented on src/test/java/stepDefinition/BookNowTopMenuSteps.java
> +public class BookNowTopMenuSteps {
Done

2022-08-12 13:00 UTC, MlulekiN commented on src/test/java/stepDefinition/BookNowTopMenuSteps.java
> +        WebElement bookNowContentPage = driver.findElement(BookNowPage.contentForm);
Done

2022-08-12 13:20 UTC, benedictnkosi requested changes

2022-08-12 13:20 UTC, benedictnkosi commented on src/test/java/stepDefinition/MenuSteps.java
> +
add theUserClicksOnTheTopColumn to this class

2022-08-12 13:20 UTC, benedictnkosi commented on src/test/java/stepDefinition/MenuSteps.java
> +    @Then("User validates content form is displayed")
this is not a menu step

2022-08-12 13:20 UTC, benedictnkosi commented on src/test/java/pages/BookNowPage.java
> +    public static By contentForm = By.xpath("//div[@class='booking-form-content']");
call this booking form, and stop using content form. check other classes also

2022-08-12 14:07 UTC, closed without merging